//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/adx/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("adx_SendEmailTwoFactorCodeToContact")]
	public partial class adx_SendEmailTwoFactorCodeToContactResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public adx_SendEmailTwoFactorCodeToContactResponse()
		{
		}
	}
}