//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum adx_publishingstatetransitionruleState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("adx_publishingstatetransitionrule")]
	public partial class adx_publishingstatetransitionrule : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string adx_FromState_PublishingStateId = "adx_fromstate_publishingstateid";
			public const string adx_name = "adx_name";
			public const string adx_publishingstatetransitionruleId = "adx_publishingstatetransitionruleid";
			public const string Id = "adx_publishingstatetransitionruleid";
			public const string adx_ToState_PublishingStateId = "adx_tostate_publishingstateid";
			public const string adx_WebsiteId = "adx_websiteid";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string adx_frompublishingstate_statetransition = "adx_frompublishingstate_statetransition";
			public const string adx_topublishingstate_statetransition = "adx_topublishingstate_statetransition";
			public const string adx_website_publishingstatetransition = "adx_website_publishingstatetransition";
			public const string business_unit_adx_publishingstatetransitionrule = "business_unit_adx_publishingstatetransitionrule";
			public const string lk_adx_publishingstatetransitionrule_createdby = "lk_adx_publishingstatetransitionrule_createdby";
			public const string lk_adx_publishingstatetransitionrule_createdonbehalfby = "lk_adx_publishingstatetransitionrule_createdonbehalfby";
			public const string lk_adx_publishingstatetransitionrule_modifiedby = "lk_adx_publishingstatetransitionrule_modifiedby";
			public const string lk_adx_publishingstatetransitionrule_modifiedonbehalfby = "lk_adx_publishingstatetransitionrule_modifiedonbehalfby";
			public const string owner_adx_publishingstatetransitionrule = "owner_adx_publishingstatetransitionrule";
			public const string team_adx_publishingstatetransitionrule = "team_adx_publishingstatetransitionrule";
			public const string user_adx_publishingstatetransitionrule = "user_adx_publishingstatetransitionrule";
		}
		
		public static class Relationships
		{
			public const string adx_publishingstatetransitionrule_webrole = "adx_publishingstatetransitionrule_webrole";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public adx_publishingstatetransitionrule() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "adx_publishingstatetransitionrule";
		
		public const string EntitySchemaName = "adx_publishingstatetransitionrule";
		
		public const string PrimaryIdAttribute = "adx_publishingstatetransitionruleid";
		
		public const string PrimaryNameAttribute = "adx_name";
		
		public const string EntityLogicalCollectionName = "adx_publishingstatetransitionrules";
		
		public const string EntitySetName = "adx_publishingstatetransitionrules";
		
		public const int EntityTypeCode = 10328;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier for Publishing State associated with Publishing State Transition Rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_fromstate_publishingstateid")]
		public Microsoft.Xrm.Sdk.EntityReference adx_FromState_PublishingStateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_fromstate_publishingstateid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_FromState_PublishingStateId");
				this.SetAttributeValue("adx_fromstate_publishingstateid", value);
				this.OnPropertyChanged("adx_FromState_PublishingStateId");
			}
		}
		
		/// <summary>
		/// Type the name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_name")]
		public string adx_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("adx_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_name");
				this.SetAttributeValue("adx_name", value);
				this.OnPropertyChanged("adx_name");
			}
		}
		
		/// <summary>
		/// Shows the entity instance.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_publishingstatetransitionruleid")]
		public System.Nullable<System.Guid> adx_publishingstatetransitionruleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("adx_publishingstatetransitionruleid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionruleId");
				this.SetAttributeValue("adx_publishingstatetransitionruleid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("adx_publishingstatetransitionruleId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_publishingstatetransitionruleid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.adx_publishingstatetransitionruleId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier for Publishing State associated with Publishing State Transition Rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_tostate_publishingstateid")]
		public Microsoft.Xrm.Sdk.EntityReference adx_ToState_PublishingStateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_tostate_publishingstateid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_ToState_PublishingStateId");
				this.SetAttributeValue("adx_tostate_publishingstateid", value);
				this.OnPropertyChanged("adx_ToState_PublishingStateId");
			}
		}
		
		/// <summary>
		/// Unique identifier for Website associated with Publishing State Transition Rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_websiteid")]
		public Microsoft.Xrm.Sdk.EntityReference adx_WebsiteId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_websiteid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_WebsiteId");
				this.SetAttributeValue("adx_websiteid", value);
				this.OnPropertyChanged("adx_WebsiteId");
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Enter the user who is assigned to manage the record. This field is updated every time the record is assigned to a different user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Shows the business unit that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Publishing State Transition Rule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<CrmEarlyBound.adx_publishingstatetransitionruleState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((CrmEarlyBound.adx_publishingstatetransitionruleState)(System.Enum.ToObject(typeof(CrmEarlyBound.adx_publishingstatetransitionruleState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Select the publishing state transition rule's status.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual adx_publishingstatetransitionrule_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((adx_publishingstatetransitionrule_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.ActivityPointer> adx_publishingstatetransitionrule_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.ActivityPointer>("adx_publishingstatetransitionrule_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_ActivityPointers");
				this.SetRelatedEntities<CrmEarlyBound.ActivityPointer>("adx_publishingstatetransitionrule_ActivityPointers", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_adx_alertsubscriptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_adx_alertsubscriptions")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.adx_alertsubscription> adx_publishingstatetransitionrule_adx_alertsubscriptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.adx_alertsubscription>("adx_publishingstatetransitionrule_adx_alertsubscriptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_adx_alertsubscriptions");
				this.SetRelatedEntities<CrmEarlyBound.adx_alertsubscription>("adx_publishingstatetransitionrule_adx_alertsubscriptions", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_adx_alertsubscriptions");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_adx_inviteredemptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_adx_inviteredemptions")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.adx_inviteredemption> adx_publishingstatetransitionrule_adx_inviteredemptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.adx_inviteredemption>("adx_publishingstatetransitionrule_adx_inviteredemptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_adx_inviteredemptions");
				this.SetRelatedEntities<CrmEarlyBound.adx_inviteredemption>("adx_publishingstatetransitionrule_adx_inviteredemptions", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_adx_inviteredemptions");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_adx_portalcomments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_adx_portalcomments")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.adx_portalcomment> adx_publishingstatetransitionrule_adx_portalcomments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.adx_portalcomment>("adx_publishingstatetransitionrule_adx_portalcomments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_adx_portalcomments");
				this.SetRelatedEntities<CrmEarlyBound.adx_portalcomment>("adx_publishingstatetransitionrule_adx_portalcomments", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_adx_portalcomments");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Annotations")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Annotation> adx_publishingstatetransitionrule_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Annotation>("adx_publishingstatetransitionrule_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Annotations");
				this.SetRelatedEntities<CrmEarlyBound.Annotation>("adx_publishingstatetransitionrule_Annotations", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Appointments")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Appointment> adx_publishingstatetransitionrule_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Appointment>("adx_publishingstatetransitionrule_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Appointments");
				this.SetRelatedEntities<CrmEarlyBound.Appointment>("adx_publishingstatetransitionrule_Appointments", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.AsyncOperation> adx_publishingstatetransitionrule_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.AsyncOperation>("adx_publishingstatetransitionrule_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_AsyncOperations");
				this.SetRelatedEntities<CrmEarlyBound.AsyncOperation>("adx_publishingstatetransitionrule_AsyncOperations", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.BulkDeleteFailure> adx_publishingstatetransitionrule_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.BulkDeleteFailure>("adx_publishingstatetransitionrule_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_BulkDeleteFailures");
				this.SetRelatedEntities<CrmEarlyBound.BulkDeleteFailure>("adx_publishingstatetransitionrule_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_chats
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_chats")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.chat> adx_publishingstatetransitionrule_chats
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.chat>("adx_publishingstatetransitionrule_chats", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_chats");
				this.SetRelatedEntities<CrmEarlyBound.chat>("adx_publishingstatetransitionrule_chats", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_chats");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_connections1")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Connection> adx_publishingstatetransitionrule_connections1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Connection>("adx_publishingstatetransitionrule_connections1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_connections1");
				this.SetRelatedEntities<CrmEarlyBound.Connection>("adx_publishingstatetransitionrule_connections1", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_connections1");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_connections2")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Connection> adx_publishingstatetransitionrule_connections2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Connection>("adx_publishingstatetransitionrule_connections2", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_connections2");
				this.SetRelatedEntities<CrmEarlyBound.Connection>("adx_publishingstatetransitionrule_connections2", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_connections2");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.DuplicateRecord> adx_publishingstatetransitionrule_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.DuplicateRecord>("adx_publishingstatetransitionrule_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_DuplicateBaseRecord");
				this.SetRelatedEntities<CrmEarlyBound.DuplicateRecord>("adx_publishingstatetransitionrule_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.DuplicateRecord> adx_publishingstatetransitionrule_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.DuplicateRecord>("adx_publishingstatetransitionrule_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_DuplicateMatchingRecord");
				this.SetRelatedEntities<CrmEarlyBound.DuplicateRecord>("adx_publishingstatetransitionrule_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Emails")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Email> adx_publishingstatetransitionrule_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Email>("adx_publishingstatetransitionrule_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Emails");
				this.SetRelatedEntities<CrmEarlyBound.Email>("adx_publishingstatetransitionrule_Emails", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Emails");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Faxes")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Fax> adx_publishingstatetransitionrule_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Fax>("adx_publishingstatetransitionrule_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Faxes");
				this.SetRelatedEntities<CrmEarlyBound.Fax>("adx_publishingstatetransitionrule_Faxes", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Letters")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Letter> adx_publishingstatetransitionrule_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Letter>("adx_publishingstatetransitionrule_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Letters");
				this.SetRelatedEntities<CrmEarlyBound.Letter>("adx_publishingstatetransitionrule_Letters", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Letters");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.MailboxTrackingFolder> adx_publishingstatetransitionrule_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.MailboxTrackingFolder>("adx_publishingstatetransitionrule_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_MailboxTrackingFolders");
				this.SetRelatedEntities<CrmEarlyBound.MailboxTrackingFolder>("adx_publishingstatetransitionrule_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.PhoneCall> adx_publishingstatetransitionrule_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.PhoneCall>("adx_publishingstatetransitionrule_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_PhoneCalls");
				this.SetRelatedEntities<CrmEarlyBound.PhoneCall>("adx_publishingstatetransitionrule_PhoneCalls", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.PrincipalObjectAttributeAccess> adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.PrincipalObjectAttributeAccess>("adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<CrmEarlyBound.PrincipalObjectAttributeAccess>("adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_ProcessSession")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.ProcessSession> adx_publishingstatetransitionrule_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.ProcessSession>("adx_publishingstatetransitionrule_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_ProcessSession");
				this.SetRelatedEntities<CrmEarlyBound.ProcessSession>("adx_publishingstatetransitionrule_ProcessSession", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.RecurringAppointmentMaster> adx_publishingstatetransitionrule_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.RecurringAppointmentMaster>("adx_publishingstatetransitionrule_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_RecurringAppointmentMasters");
				this.SetRelatedEntities<CrmEarlyBound.RecurringAppointmentMaster>("adx_publishingstatetransitionrule_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_SocialActivities")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.SocialActivity> adx_publishingstatetransitionrule_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.SocialActivity>("adx_publishingstatetransitionrule_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_SocialActivities");
				this.SetRelatedEntities<CrmEarlyBound.SocialActivity>("adx_publishingstatetransitionrule_SocialActivities", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_SyncErrors")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.SyncError> adx_publishingstatetransitionrule_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.SyncError>("adx_publishingstatetransitionrule_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_SyncErrors");
				this.SetRelatedEntities<CrmEarlyBound.SyncError>("adx_publishingstatetransitionrule_SyncErrors", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_Tasks")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Task> adx_publishingstatetransitionrule_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Task>("adx_publishingstatetransitionrule_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_Tasks");
				this.SetRelatedEntities<CrmEarlyBound.Task>("adx_publishingstatetransitionrule_Tasks", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N adx_publishingstatetransitionrule_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.UserEntityInstanceData> adx_publishingstatetransitionrule_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.UserEntityInstanceData>("adx_publishingstatetransitionrule_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_UserEntityInstanceDatas");
				this.SetRelatedEntities<CrmEarlyBound.UserEntityInstanceData>("adx_publishingstatetransitionrule_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:N adx_publishingstatetransitionrule_webrole
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_publishingstatetransitionrule_webrole")]
		public System.Collections.Generic.IEnumerable<CrmEarlyBound.Adx_webrole> adx_publishingstatetransitionrule_webrole
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<CrmEarlyBound.Adx_webrole>("adx_publishingstatetransitionrule_webrole", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_publishingstatetransitionrule_webrole");
				this.SetRelatedEntities<CrmEarlyBound.Adx_webrole>("adx_publishingstatetransitionrule_webrole", null, value);
				this.OnPropertyChanged("adx_publishingstatetransitionrule_webrole");
			}
		}
		
		/// <summary>
		/// N:1 adx_frompublishingstate_statetransition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_fromstate_publishingstateid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_frompublishingstate_statetransition")]
		public CrmEarlyBound.Adx_publishingstate adx_frompublishingstate_statetransition
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.Adx_publishingstate>("adx_frompublishingstate_statetransition", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_frompublishingstate_statetransition");
				this.SetRelatedEntity<CrmEarlyBound.Adx_publishingstate>("adx_frompublishingstate_statetransition", null, value);
				this.OnPropertyChanged("adx_frompublishingstate_statetransition");
			}
		}
		
		/// <summary>
		/// N:1 adx_topublishingstate_statetransition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_tostate_publishingstateid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_topublishingstate_statetransition")]
		public CrmEarlyBound.Adx_publishingstate adx_topublishingstate_statetransition
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.Adx_publishingstate>("adx_topublishingstate_statetransition", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_topublishingstate_statetransition");
				this.SetRelatedEntity<CrmEarlyBound.Adx_publishingstate>("adx_topublishingstate_statetransition", null, value);
				this.OnPropertyChanged("adx_topublishingstate_statetransition");
			}
		}
		
		/// <summary>
		/// N:1 adx_website_publishingstatetransition
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_websiteid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_website_publishingstatetransition")]
		public CrmEarlyBound.Adx_website adx_website_publishingstatetransition
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.Adx_website>("adx_website_publishingstatetransition", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_website_publishingstatetransition");
				this.SetRelatedEntity<CrmEarlyBound.Adx_website>("adx_website_publishingstatetransition", null, value);
				this.OnPropertyChanged("adx_website_publishingstatetransition");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_adx_publishingstatetransitionrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_adx_publishingstatetransitionrule")]
		public CrmEarlyBound.BusinessUnit business_unit_adx_publishingstatetransitionrule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.BusinessUnit>("business_unit_adx_publishingstatetransitionrule", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_adx_publishingstatetransitionrule_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_adx_publishingstatetransitionrule_createdby")]
		public CrmEarlyBound.SystemUser lk_adx_publishingstatetransitionrule_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_adx_publishingstatetransitionrule_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_adx_publishingstatetransitionrule_createdonbehalfby")]
		public CrmEarlyBound.SystemUser lk_adx_publishingstatetransitionrule_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_adx_publishingstatetransitionrule_createdonbehalfby");
				this.SetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_adx_publishingstatetransitionrule_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_adx_publishingstatetransitionrule_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_adx_publishingstatetransitionrule_modifiedby")]
		public CrmEarlyBound.SystemUser lk_adx_publishingstatetransitionrule_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_adx_publishingstatetransitionrule_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_adx_publishingstatetransitionrule_modifiedonbehalfby")]
		public CrmEarlyBound.SystemUser lk_adx_publishingstatetransitionrule_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_adx_publishingstatetransitionrule_modifiedonbehalfby");
				this.SetRelatedEntity<CrmEarlyBound.SystemUser>("lk_adx_publishingstatetransitionrule_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_adx_publishingstatetransitionrule_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 owner_adx_publishingstatetransitionrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_adx_publishingstatetransitionrule")]
		public CrmEarlyBound.Owner owner_adx_publishingstatetransitionrule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.Owner>("owner_adx_publishingstatetransitionrule", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("owner_adx_publishingstatetransitionrule");
				this.SetRelatedEntity<CrmEarlyBound.Owner>("owner_adx_publishingstatetransitionrule", null, value);
				this.OnPropertyChanged("owner_adx_publishingstatetransitionrule");
			}
		}
		
		/// <summary>
		/// N:1 team_adx_publishingstatetransitionrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_adx_publishingstatetransitionrule")]
		public CrmEarlyBound.Team team_adx_publishingstatetransitionrule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.Team>("team_adx_publishingstatetransitionrule", null);
			}
		}
		
		/// <summary>
		/// N:1 user_adx_publishingstatetransitionrule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_adx_publishingstatetransitionrule")]
		public CrmEarlyBound.SystemUser user_adx_publishingstatetransitionrule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<CrmEarlyBound.SystemUser>("user_adx_publishingstatetransitionrule", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public adx_publishingstatetransitionrule(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["adx_publishingstatetransitionruleid"] = base.Id;
                        break;
                    case "adx_publishingstatetransitionruleid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}