//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExportSolutionAsync")]
	public partial class ExportSolutionAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ExportSolutionAsyncResponse()
		{
		}
		
		public System.Guid AsyncOperationId
		{
			get
			{
				if (this.Results.Contains("AsyncOperationId"))
				{
					return ((System.Guid)(this.Results["AsyncOperationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
		}
		
		public System.Guid ExportJobId
		{
			get
			{
				if (this.Results.Contains("ExportJobId"))
				{
					return ((System.Guid)(this.Results["ExportJobId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
		}
	}
}