//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("GetSearchInformation")]
	public partial class GetSearchInformationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public GetSearchInformationResponse()
		{
		}
		
		public string CanAllowLeadingWildCardSearch
		{
			get
			{
				if (this.Results.Contains("CanAllowLeadingWildCardSearch"))
				{
					return ((string)(this.Results["CanAllowLeadingWildCardSearch"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string CanSupportedByRelevanceSearch
		{
			get
			{
				if (this.Results.Contains("CanSupportedByRelevanceSearch"))
				{
					return ((string)(this.Results["CanSupportedByRelevanceSearch"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}