//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SLACustomTimeCalculationTemplate")]
	public partial class msdyn_SLACustomTimeCalculationTemplateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SLACustomTimeCalculationTemplateResponse()
		{
		}
		
		public string firstOutputValue
		{
			get
			{
				if (this.Results.Contains("firstOutputValue"))
				{
					return ((string)(this.Results["firstOutputValue"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string returnCalendarId
		{
			get
			{
				if (this.Results.Contains("returnCalendarId"))
				{
					return ((string)(this.Results["returnCalendarId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string secondOutputValue
		{
			get
			{
				if (this.Results.Contains("secondOutputValue"))
				{
					return ((string)(this.Results["secondOutputValue"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}