//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DeleteCalendar")]
	public partial class msdyn_DeleteCalendarResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_DeleteCalendarResponse()
		{
		}
		
		public string InnerCalendarIds
		{
			get
			{
				if (this.Results.Contains("InnerCalendarIds"))
				{
					return ((string)(this.Results["InnerCalendarIds"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}