//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msft_DataEngineIndexMgmt_GetIndexInfo")]
	public partial class msft_DataEngineIndexMgmt_GetIndexInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msft_DataEngineIndexMgmt_GetIndexInfoResponse()
		{
		}
		
		public bool ExistsInMetaData
		{
			get
			{
				if (this.Results.Contains("ExistsInMetaData"))
				{
					return ((bool)(this.Results["ExistsInMetaData"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public bool ExistsInSqlDB
		{
			get
			{
				if (this.Results.Contains("ExistsInSqlDB"))
				{
					return ((bool)(this.Results["ExistsInSqlDB"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public bool IsQueuedForAdhocIndexing
		{
			get
			{
				if (this.Results.Contains("IsQueuedForAdhocIndexing"))
				{
					return ((bool)(this.Results["IsQueuedForAdhocIndexing"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}