//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RetrieveAadUserSetOfPrivilegesByNames")]
	public partial class RetrieveAadUserSetOfPrivilegesByNamesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid DirectoryObjectId
		{
			get
			{
				if (this.Parameters.Contains("DirectoryObjectId"))
				{
					return ((System.Guid)(this.Parameters["DirectoryObjectId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["DirectoryObjectId"] = value;
			}
		}
		
		public string[] PrivilegeNames
		{
			get
			{
				if (this.Parameters.Contains("PrivilegeNames"))
				{
					return ((string[])(this.Parameters["PrivilegeNames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["PrivilegeNames"] = value;
			}
		}
		
		public RetrieveAadUserSetOfPrivilegesByNamesRequest()
		{
			this.RequestName = "RetrieveAadUserSetOfPrivilegesByNames";
			this.DirectoryObjectId = default(System.Guid);
			this.PrivilegeNames = default(string[]);
		}
	}
}