//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RetrieveFlowUpdates")]
	public partial class RetrieveFlowUpdatesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public RetrieveFlowUpdatesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection FlowUpdates
		{
			get
			{
				if (this.Results.Contains("FlowUpdates"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["FlowUpdates"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}