//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("Share")]
	public partial class ShareResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ShareResponse()
		{
		}
		
		public string sharingresponse
		{
			get
			{
				if (this.Results.Contains("sharingresponse"))
				{
					return ((string)(this.Results["sharingresponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}