//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmEarlyBound
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum SharePoint_ValidationStatusReason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Authentication failure.", 5)]
		Authenticationfailure = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invalid certificates.", 6)]
		Invalidcertificates = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The URL could not be accessed because of Internet Explorer security settings.", 4)]
		TheURLcouldnotbeaccessedbecauseofInternetExplorersecuritysettings = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The URL schemes of Microsoft Dynamics 365 and SharePoint are different.", 3)]
		TheURLschemesofMicrosoftDynamics365andSharePointaredifferent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL has not been validated.", 0)]
		ThisrecordsURLhasnotbeenvalidated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL is not valid.", 2)]
		ThisrecordsURLisnotvalid = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("This record\'s URL is valid.", 1)]
		ThisrecordsURLisvalid = 2,
	}
}